import {test,expect,type Page,type APIRequestContext} from './atlas-fixtures.js';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
test.setTimeout(60000);
test.use({extraHTTPHeaders:{Origin:'http://127.0.0.1:4311'}});
const catalog = [
 ['101','Generate','Editor empty'],['102','Generate','Source and fixed seed'],['103','Inputs','Source and style reference'],['104','Inputs','Change source'],['105','Generate','Waiting for compatible worker'],['106','Generate','Older Image worker'],['107','Activity','Loading image editor'],['108','Activity','Editing and cancellation'],['109','Activity','Failed edit'],['110','Preview','Completed edit'],['111','Generate','Isolated persisted drafts'],['112','Preview','Replace existing edit draft'],['113','Chat','Image editing approval'],['114','Chat','Review editing inputs'],['115','Chat','Approved edit'],['116','Inputs','Invalid source file'],['117','Generate','Apply saved image as source'],
] as const;
const root=path.resolve('.local/image-edit-atlas');
async function select(page:Page,name:string){if(!await page.getByRole('button',{name,exact:true}).isVisible())await page.getByRole('button',{name:'Toggle sidebar',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();}
async function scenario(request:APIRequestContext,name:string){expect((await request.post('/__qa/scenario',{data:{scenario:name}})).ok()).toBeTruthy();}
async function launch(request:APIRequestContext){const offers=await(await request.get('/api/v1/pool/offers?worker_class=image')).json();const offer=offers.items[0];expect((await request.post('/api/v1/pool/launch',{headers:{'Idempotency-Key':crypto.randomUUID()},data:{selections:[{offer_id:offer.id,quantity:1}],max_hourly:offer.hourly}})).ok()).toBeTruthy();await expect.poll(async()=>(await(await request.get('/api/v1/pool')).json()).workers.some((w:any)=>w.state==='ready'),{timeout:20000}).toBeTruthy();}
const source=async(name='mountain-lake-source.png',color='#587786')=>({name,mimeType:'image/png',buffer:await sharp(Buffer.from(`<svg width="960" height="640"><rect width="960" height="640" fill="${color}"/><circle cx="710" cy="150" r="70" fill="#e9dcae"/><path d="M0 500L280 170L580 500L770 320L960 510V640H0Z" fill="#344f3c"/><path d="M0 535Q400 470 960 550V640H0Z" fill="#8bb9bd"/></svg>`)).png().toBuffer()});
async function addSource(page:Page){await page.getByLabel('Choose reference files').setInputFiles(await source());await expect(page.locator('.reference-thumb')).toHaveCount(1);await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('button',{name:'Add references',exact:true})).toBeEnabled();}
for(const device of ['desktop','mobile'] as const)for(const [id,surface,title] of catalog)test(`${id} ${device} ${title}`,async({page,request},testInfo)=>{
 const width=device==='desktop'?1440:390,height=device==='desktop'?1000:844;await page.setViewportSize({width,height});await mkdir(path.join(root,device),{recursive:true});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));let completed=false;
 try{
  await page.addInitScript(()=>Object.defineProperty(Crypto.prototype,'randomUUID',{value:undefined}));await page.goto('/');await select(page,'Image to image');await expect(page.getByLabel('Prompt',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'LoRAs',exact:true})).toHaveCount(0);
  if(id==='101'){await expect(page.getByRole('button',{name:/^Create image/})).toBeDisabled();}
  else if(id==='116'){await page.getByLabel('Choose reference files').setInputFiles({name:'broken.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(page.getByRole('alert')).toContainText('cannot preview');}
  else if(['113','114','115'].includes(id)){
   await page.goto('/chat');await page.locator('input[type=file]').setInputFiles(await source());await page.getByRole('button',{name:'Save',exact:true}).click();const composer=page.getByRole('combobox',{name:'Chat message'});await composer.fill('/image-to-image Make the sky pink, keeping the mountains.');await expect(page.getByRole('button',{name:'Send',exact:true})).toBeEnabled();await composer.press('Enter');await expect(page.getByRole('button',{name:'Approve',exact:true})).toBeEnabled({timeout:20000});
   if(id==='114'){await page.getByRole('button',{name:'Edit request',exact:true}).click();await expect(page.getByRole('button',{name:'+ Add input',exact:true})).toBeVisible();}
   if(id==='115'){await launch(request);await page.getByRole('button',{name:'Approve',exact:true}).click();await expect.poll(async()=>(await(await request.get('/api/v1/jobs')).json()).items.some((j:any)=>j.state==='completed'),{timeout:20000}).toBeTruthy();if(await page.getByRole('dialog',{name:'GPU workers',exact:true}).isVisible())await page.getByRole('button',{name:'Close GPU workers'}).click();await expect(page.locator('.job-output-tile.completed')).toHaveCount(1);}
  } else {
   await addSource(page);await page.getByLabel('Prompt',{exact:true}).fill('Change the sky to a soft pink sunset. Preserve the mountains and the lake.');
   if(['102','103','104'].includes(id)){await page.getByLabel('Seed mode').selectOption('fixed');await page.getByLabel('Starting seed').fill('42');await page.getByLabel('Quantity',{exact:true}).selectOption('4');}
   if(['103','104'].includes(id)){await page.getByLabel('Choose reference files').setInputFiles(await source('a-very-long-name-for-the-warm-color-palette-reference-image.png','#d19a93'));await expect(page.locator('.reference-thumb')).toHaveCount(2);await page.getByRole('button',{name:'Save',exact:true}).click();if(id==='104'){await page.locator('.reference-thumb').nth(1).click();await page.getByLabel(/^Role for/).selectOption('source');await expect(page.getByLabel(/^Role for/)).toHaveValue('source');}}
   if(['105','106','107','108','109','110'].includes(id)){
    if(id==='106'){await scenario(request,'legacy_image');await launch(request);}else if(!['105'].includes(id))await launch(request);
    if(id==='107')await scenario(request,'model_loading');if(id==='108')await scenario(request,'generating');if(id==='109')await scenario(request,'generation_failure');
    await page.getByRole('button',{name:/^Create image/}).click();
    await expect(page.locator('.generate-feedback')).toBeAttached();if(!['105','106'].includes(id)&&await page.getByRole('dialog',{name:'GPU workers',exact:true}).isVisible())await page.getByRole('button',{name:'Close GPU workers'}).click();
    if(['105','106'].includes(id)){await expect(page.getByRole('dialog',{name:'GPU workers',exact:true})).toBeVisible();await page.getByRole('button',{name:'Close GPU workers'}).click();await expect(page.getByRole('region',{name:'Latest generation'})).toContainText('queued');await page.getByRole('button',{name:'View progress',exact:true}).click();await expect(page.getByRole('region',{name:'Selected output'}).getByText(/with image editing support/)).toBeVisible();}
    if(['107','108'].includes(id)){await page.getByRole('button',{name:'View progress',exact:true}).click();if(id==='107')await expect(page.getByText('Loading image editor',{exact:true})).toBeVisible({timeout:20000});else {await expect(page.getByText('Editing · 32%',{exact:true})).toBeVisible({timeout:20000});await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect.poll(async()=>(await(await request.get('/api/v1/jobs')).json()).items[0].state,{timeout:15000}).toBe('cancelled');await expect(page.getByText('This output was cancelled.',{exact:true})).toBeVisible();}}
    if(id==='109'){await expect(page.getByRole('button',{name:'View issue'})).toBeVisible({timeout:15000});await page.getByRole('button',{name:'View issue'}).click();await expect(page.getByRole('button',{name:'Retry',exact:true})).toBeVisible();}
    if(id==='110'){await expect(page.getByRole('button',{name:'Open image 1 preview'})).toBeVisible({timeout:20000});await page.getByRole('button',{name:'Open image 1 preview'}).click();await expect(page.getByRole('button',{name:'Edit image',exact:true})).toBeVisible();}
   }
   if(id==='111'){await select(page,'Reference to video');await expect(page.locator('.reference-thumb')).toHaveCount(0);await page.getByLabel('Prompt',{exact:true}).fill('Video draft');await select(page,'Image to image');await expect(page.locator('.reference-thumb')).toHaveCount(1);await page.reload();await select(page,'Image to image');await expect(page.locator('.reference-thumb')).toHaveCount(1);await expect(page.getByLabel('Prompt',{exact:true})).toContainText('soft pink');}
   if(['112','117'].includes(id)){await page.goto('/library');await page.locator('.library-grid img').first().click();await page.getByRole('button',{name:'Edit image',exact:true}).click();await expect(page.getByRole('dialog',{name:'Replace editing draft',exact:true})).toBeVisible();if(id==='117'){await page.getByRole('button',{name:'Replace draft',exact:true}).click();if(await page.getByRole('dialog',{name:'Describe assets'}).isVisible())await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.reference-thumb')).toHaveCount(1);await expect(page.getByLabel('Prompt',{exact:true})).toBeEmpty();await expect(page.getByRole('button',{name:/^Create image/})).toBeDisabled();}}
  }
  if(id==='103') { await page.getByLabel('Prompt',{exact:true}).focus(); await page.getByLabel('Prompt',{exact:true}).blur(); }
  expect(errors).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);completed=true;
 }finally{
  await page.evaluate(async()=>{await document.fonts.ready;await new Promise(requestAnimationFrame);(document.activeElement as HTMLElement)?.blur();window.scrollTo({top:0,behavior:'instant'});await new Promise(requestAnimationFrame);});const file=`${device}/${id}-${title.toLowerCase().replace(/[^a-z0-9]+/g,'-')}.png`;await page.screenshot({path:path.join(root,file),fullPage:!await page.getByRole('dialog').count(),animations:'disabled'});const captures: Array<{position:string;file:string}>=[];const scroller=page.locator('.review-body').filter({visible:true}).first();if(completed&&await scroller.count()){const size=await scroller.evaluate(e=>({height:e.clientHeight,total:e.scrollHeight}));if(size.total>size.height+4){await scroller.evaluate(e=>e.scrollTop=e.scrollHeight);const extra=file.replace('.png','-settings.png');await page.screenshot({path:path.join(root,extra),animations:'disabled'});captures.push({position:'Remaining settings',file:extra});}}await writeFile(path.join(root,device,id+'.json'),JSON.stringify({id,title,surface,device,viewport:{width,height},status:completed?'passed':'failed',file,captures,test:testInfo.title},null,2));await testInfo.attach(title,{path:path.join(root,file),contentType:'image/png'});
 }
});
