import {test,expect} from './fixtures.js';
import fs from 'node:fs/promises';
test('input mentions insert at the caret, preserve slots, preview and block missing inputs',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 const references:any[]=[{id:'image',asset_id:'image',kind:'image',role:'reference',framing:'fit'},{id:'video',asset_id:'video',kind:'video',role:'reference',include_audio:true,range:{start_seconds:0,duration_seconds:3}},{id:'audio',asset_id:'audio',kind:'audio',role:'reference',range:{start_seconds:0,duration_seconds:3}}];
 const assets=references.map(r=>({id:r.asset_id,kind:r.kind,name:r.kind==='image'?'Forest.png':r.kind==='video'?'Camera movement.mp4':'Ambience.wav',note:'',metadata:{duration:5,width:480,height:270}}));
 const request={workflow:'reference-to-video',mode:'sfw',prompt:'Before after',count:1,seed:'random',output:{aspect:'16:9',size:'768p',duration_seconds:5},references};
 let chat:any={id:'mentions',title:'Input mentions',mode:'sfw',workflow:'reference-to-video',version:0,epoch:0,activity:'idle',reasoning:true,assets:[],asset_manifest:assets,jobs:[],messages:[],groups:[{id:'g',state:'reviewing',cards:[{id:'c',workflow:'reference-to-video',revisions:[{number:1,request,decision:'undecided',job_ids:[],notes:{}}]}]}]};
 let posted:any;
 await page.route('**/api/v1/chat-config',r=>r.fulfill({json:{configured:true}}));
 await page.route('**/api/v1/chats**',r=>{const req=r.request(),path=new URL(req.url()).pathname;if(path.endsWith('/messages')&&req.method()==='POST'){posted=req.postDataJSON();chat={...chat,messages:[{id:'m',role:'user',text:posted.text,assets:posted.assets}],version:1};}return r.fulfill({json:path==='/api/v1/chats'?{items:[]}:chat});});
 await page.route('**/api/v1/assets/*',r=>r.fulfill({json:assets.find(a=>r.request().url().endsWith(a.id))??{}}));
 await page.route('**/api/v1/assets/*/content',async r=>r.request().url().includes('/video/')?r.fulfill({contentType:'video/mp4',body:await fs.readFile('.local/browser-preview.mp4')}):r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="480" height="270"><rect width="480" height="270" fill="#49604b"/><circle cx="360" cy="60" r="35" fill="#ead080"/></svg>'}));
 let savedNote='',failNote=true;
 await page.route('**/api/v1/notes/*',r=>{if(r.request().method()==='PUT'){if(failNote)return r.fulfill({status:409,json:{error:{message:'Please try again'}}});savedNote=r.request().postDataJSON().note;}return r.fulfill({json:{note:savedNote,revision:1}});});
 await page.setViewportSize({width:1200,height:950});await page.goto('/chat?chat=mentions');
 await page.locator('.job-chat-wrap').getByRole('button',{name:'Preview Forest.png'}).click();
 await page.getByRole('button',{name:'Edit note',exact:true}).click();await page.getByRole('textbox',{name:'Asset note'}).fill('Forest reference');await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.locator('.viewer-note-panel')).toContainText('Please try again');failNote=false;await page.getByRole('button',{name:'Save note',exact:true}).click();await expect(page.locator('.viewer-note-panel')).toHaveCount(0);await page.getByRole('button',{name:'Edit note',exact:true}).click();await expect(page.getByRole('textbox',{name:'Asset note'})).toHaveValue('Forest reference');await page.getByRole('button',{name:'Edit note',exact:true}).click();
 await expect(page.getByRole('navigation',{name:'Input navigation'})).toContainText('1 of 3');await expect(page.getByRole('button',{name:'Previous input'})).toBeDisabled();
 await page.getByRole('button',{name:'Next input'}).click();await expect(page.locator('.viewer-reference-label')).toHaveText('Video 1');await expect(page.locator('.viewer-canvas video')).toBeVisible();
 await page.getByRole('button',{name:'Next input'}).click();await expect(page.getByRole('navigation',{name:'Input navigation'})).toContainText('3 of 3');await expect(page.getByRole('button',{name:'Next input'})).toBeDisabled();await expect(page.locator('.viewer-canvas audio')).toBeVisible();
 await page.getByRole('button',{name:'Previous input'}).click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/input-navigation-mobile.png'});
 await page.getByRole('button',{name:'Previous input'}).click();await page.locator('.preview-image-surface').dblclick();await expect(page.getByRole('button',{name:'Reset zoom'})).toBeVisible();
 await page.getByRole('button',{name:'Next input'}).click();await expect(page.locator('.viewer-canvas video')).toBeVisible();
 let releasePreview!:()=>void;const delayedPreview=new Promise<void>(resolve=>{releasePreview=resolve;});
 await page.route('**/api/v1/assets/image',async r=>{await delayedPreview;return r.fulfill({json:assets[0]});});
 const loading=page.waitForRequest(r=>r.url().endsWith('/api/v1/assets/image'));
 await page.getByRole('button',{name:'Previous input'}).click();await loading;
 await page.goBack();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page).toHaveURL(/\/chat\?chat=mentions$/);
 const finished=page.waitForResponse(r=>r.url().endsWith('/api/v1/assets/image'));releasePreview();await finished;
 await page.setViewportSize({width:1200,height:950});await page.getByRole('button',{name:'Review / history',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Review generation'}),editor=dialog.getByRole('combobox',{name:'Prompt'});
 await editor.click();await page.keyboard.press('Control+Home');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');
 await dialog.getByRole('button',{name:'Picture 1',exact:true}).click();await expect(editor).toHaveText('Before Picture 1 after');
 expect(await editor.evaluate(e=>e.clientWidth>e.parentElement!.clientWidth*.9)).toBe(true);await editor.fill('Use @');await expect(dialog.getByRole('listbox',{name:'Input references'})).toBeVisible();await expect(dialog.getByRole('option').filter({hasText:'Picture 1'}).locator('img')).toBeVisible();
 await fs.mkdir('.local/input-mentions',{recursive:true});await page.screenshot({path:'.local/input-mentions/review-desktop.png'});
 await page.setViewportSize({width:390,height:950});await page.screenshot({path:'.local/input-mentions/review-mobile.png'});expect(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);
 await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(editor.locator('.input-mention')).toHaveText('Audio 2');
 await dialog.getByRole('button',{name:'Edit Video 1',exact:true}).click();await dialog.getByLabel('Include source audio').uncheck();await expect(editor.locator('.input-mention')).toHaveText('Audio 1');
 await dialog.getByLabel('More options for Audio 1').click();await dialog.getByRole('button',{name:'Remove',exact:true}).click();await expect(editor.locator('.missing')).toHaveText('Missing input');await expect(dialog.getByRole('button',{name:'Save changes'})).toBeDisabled();
 await dialog.getByRole('button',{name:'Close review'}).click();const composer=page.getByRole('combobox',{name:'Chat message'});await composer.fill('Use @');await expect(page.getByRole('option').first()).toContainText('Earlier in chat');await page.screenshot({path:'.local/input-mentions/chat-mobile.png'});
 await page.getByRole('option').first().click();await expect(page.locator('.composer-attachments')).toContainText('Forest.png');await composer.locator('.input-mention').click();await expect(page.getByRole('dialog',{name:'Media preview'})).toBeVisible();await expect(page.locator('.viewer-reference-label')).toHaveText('Picture 1');await page.screenshot({path:'.local/labeled-preview.png'});await page.getByRole('button',{name:'Close preview'}).click();
 await page.getByRole('button',{name:'Send',exact:true}).click();await expect.poll(()=>posted?.assets).toEqual(['image']);expect(posted.text).toBe('Use [Picture 1](asset:image) ');await expect(page.getByRole('button',{name:'Use in next message'})).toHaveCount(0);await page.locator('.history-attachments').getByRole('button',{name:'Preview Forest.png'}).click();await expect(page.getByRole('dialog',{name:'Media preview'})).toBeVisible();await expect(page.locator('.viewer-reference-label')).toHaveText('Picture 1');await page.screenshot({path:'.local/labeled-preview.png'});await page.getByRole('button',{name:'Close preview',exact:true}).click();await page.screenshot({path:'.local/history-thumbnails.png'});await expect(page.locator('.chat-message.user .input-mention')).toHaveText('Picture 1');expect(errors).toEqual([]);
});

test('Generate inserts references mid-prompt and renders the same picker',async({page})=>{
 const reference={id:'image',asset_id:'image',kind:'image',role:'reference',framing:'fit'};
 const request={workflow:'reference-to-video',prompt:'Before after',mode:'sfw',seed:'random',count:1,references:[reference],output:{aspect:'16:9',size:'768p',duration_seconds:5}};
 await page.route('**/api/v1/jobs/original',r=>r.fulfill({json:{id:'original',request,seed:'42'}}));
 await page.route('**/api/v1/assets/image',r=>r.fulfill({json:{name:'Forest.png',kind:'image',mime_type:'image/png'}}));
 await page.route('**/api/v1/assets/image/content',r=>r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="480" height="270"><rect width="480" height="270" fill="#49604b"/><circle cx="360" cy="60" r="35" fill="#ead080"/></svg>'}));
 await page.setViewportSize({width:1200,height:950});await page.goto('/?fromJob=original&seed=same');
 const editor=page.getByRole('combobox',{name:'Prompt',exact:true});await expect(editor).toHaveText('Before after');await editor.click();await page.keyboard.press('Control+Home');for(let i=0;i<7;i++)await page.keyboard.press('ArrowRight');
 await page.getByRole('button',{name:'<Picture 1>',exact:true}).click();await expect(editor).toHaveText('Before Picture 1 after');
 await editor.fill('Use @');await page.screenshot({path:'.local/input-mentions/generate-desktop.png'});await page.setViewportSize({width:390,height:950});await page.screenshot({path:'.local/input-mentions/generate-mobile.png'});expect(await editor.evaluate(e=>e.clientWidth>e.parentElement!.clientWidth*.9)).toBe(true);
 await page.getByRole('listbox',{name:'Input references'}).getByRole('option').click();await page.keyboard.press('Backspace');await page.keyboard.press('Backspace');await expect(editor.locator('.input-mention')).toHaveCount(0);await expect(editor).toHaveText('Use ');
});
