import React,{useEffect,useRef} from 'react';
export function ChatSidebarRow({title,selected,status,working,unread,onOpen,onRename,onDelete}:{title:string;selected:boolean;status?:string;working?:boolean;unread?:boolean;onOpen:()=>void;onRename:()=>void;onDelete:()=>void}){
 const menu=useRef<HTMLDivElement>(null),button=useRef<HTMLButtonElement>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),origin=useRef({x:0,y:0}),held=useRef(false);
 function cancel(){clearTimeout(timer.current);}
 useEffect(()=>{function dismiss(event:PointerEvent){const target=event.target as Node;if(menu.current?.matches(':popover-open')&&!menu.current.contains(target)&&!button.current?.contains(target))menu.current.hidePopover();}document.addEventListener('pointerdown',dismiss,true);return()=>{cancel();document.removeEventListener('pointerdown',dismiss,true);};},[]);
 function show(x:number,y:number){cancel();held.current=true;const el=menu.current;if(!el)return;el.style.left=Math.max(8,Math.min(x,innerWidth-188))+'px';el.style.top=Math.max(8,Math.min(y,innerHeight-104))+'px';el.showPopover();el.querySelector('button')?.focus();}
 function close(){menu.current?.hidePopover();button.current?.focus();}
 return <><button ref={button} className={'chat-sidebar-row'+(selected?' selected':'')} aria-label={'Open chat: '+title} aria-haspopup="menu" onPointerDown={e=>{held.current=false;if(!e.isPrimary||e.button!==0)return;origin.current={x:e.clientX,y:e.clientY};timer.current=setTimeout(()=>show(e.clientX,e.clientY),550);}} onPointerMove={e=>{if(Math.hypot(e.clientX-origin.current.x,e.clientY-origin.current.y)>8)cancel();}} onPointerUp={e=>{cancel();if(held.current)e.preventDefault();}} onPointerCancel={cancel} onPointerLeave={cancel} onContextMenu={e=>{e.preventDefault();show(e.clientX,e.clientY);}} onKeyDown={e=>{if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){e.preventDefault();const r=e.currentTarget.getBoundingClientRect();show(r.left,r.bottom);} }} onClick={()=>{if(held.current){held.current=false;return;}onOpen();}}><span className="chat-sidebar-title">{title}{status&&<small>{status}</small>}</span>{working?<span className="chat-working" role="status" aria-label="Working" title="Working"/>:unread?<span className="chat-unread" aria-label="Unread message" title="Unread message"/>:null}</button>
 <div ref={menu} popover="manual" role="menu" aria-label={'Chat actions: '+title} className="chat-context-menu" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const options=Array.from(e.currentTarget.querySelectorAll('button'));const index=options.indexOf(document.activeElement as HTMLButtonElement);options[(index+1)%options.length]?.focus();}}}><button role="menuitem" onClick={()=>{close();onRename();}}>Rename</button><button role="menuitem" className="danger" onClick={()=>{close();onDelete();}}>Delete</button></div></>;
}
