import React,{useEffect,useRef,useState} from 'react';
import './request-controls.css';
export function AspectPicker({value,onChange,disabled=false}:{value:string;onChange:(v:'16:9'|'9:16')=>void;disabled?:boolean}){
 const ref=useRef<HTMLDetailsElement>(null);useEffect(()=>{const close=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node))ref.current?.removeAttribute('open');};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 const option=(v:string)=><><span className={'aspect-symbol '+(v==='9:16'?'portrait':'')}/><span>{v==='9:16'?'Portrait':'Landscape'}<small>{v}</small></span></>;
 return <details ref={ref} className="aspect-picker" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();ref.current?.removeAttribute('open');}}}><summary aria-label="Aspect ratio" aria-disabled={disabled} onClick={e=>{if(disabled)e.preventDefault();}}>{option(value)}<span className="picker-chevron">⌄</span></summary><div>{(['16:9','9:16'] as const).map(v=><button type="button" key={v} disabled={disabled} aria-pressed={v===value} onClick={()=>{onChange(v);ref.current?.removeAttribute('open');}}>{option(v)}</button>)}</div></details>;
}
export function BatchPicker({value,onChange}:{value:number;onChange:(n:number)=>void}){return <select aria-label="Quantity" value={value} onChange={e=>onChange(Number(e.target.value))}>{Array.from({length:16},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select>;}
export function LengthPicker({value,step=1,onChange}:{value:number;step?:number;onChange:(n:number)=>void}){const values=step===1?Array.from({length:11},(_,i)=>i+5):[5,10,15];return <select aria-label="Length" value={value} onChange={e=>onChange(Number(e.target.value))}>{!values.includes(value)&&<option value={value} disabled>{value} seconds</option>}{values.map(v=><option value={v} key={v}>{v} seconds</option>)}</select>;}
export function SeedControl({random,value,onChange}:{random:boolean;value:string;onChange:(random:boolean,value:string)=>void}){const [last,setLast]=useState(random?'0':value);useEffect(()=>{if(!random)setLast(value);},[random,value]);return <div className="seed-controls"><label>Seed<select aria-label="Seed mode" value={random?'random':'fixed'} onChange={e=>onChange(e.target.value==='random',last)}><option value="random">Random</option><option value="fixed">Fixed</option></select></label>{!random&&<label>Starting seed<input aria-label="Starting seed" inputMode="numeric" maxLength={16} value={value} onChange={e=>onChange(false,e.target.value)}/></label>}<small>{random?'A different seed for each output.':'Seeds increase by 1 for each output.'}</small></div>;}
