import {clientId} from './identity.js';
import React,{useState,useRef,useEffect} from 'react';
import type {ImageRequest} from '../shared/generation.js';
import type {RequestAsset} from './request-fields.js';
import type {PreviewRequestInput} from './request-preview.js';
import {AssetThumbnail} from './asset-thumbnail.js';
import {RequestDialog} from './request-dialog.js';
import './request-inputs.css';
type Ref=NonNullable<ImageRequest['references']>[number];
const kindName=(kind:string)=>kind==='image'?'Image':kind==='video'?'Video':'Audio';
function InputRow({reference:r,label,asset,first,last,change,move,remove,onPreview,onInsert,editingImage=false}:{editingImage?:boolean;onInsert?:()=>void;reference:Ref;label:string;asset?:RequestAsset;first:boolean;last:boolean;change:(v:Partial<Ref>)=>void;move:(delta:number)=>void;remove:()=>void;onPreview:()=>void}){
 const menu=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{const close=(e:PointerEvent)=>{if(menu.current&&!menu.current.contains(e.target as Node))menu.current.open=false;};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 const [editing,setEditing]=useState(false),[info,setInfo]=useState(false);
 const summary=r.kind==='image'?`${r.role==='source'?'Source image':r.role==='first_frame'?'First frame':r.role==='last_frame'?'Last frame':'Reference'}${editingImage?'':` · ${r.framing==='fill'?'Fill':'Fit'}`}`:`Use clip: ${r.range?.start_seconds??0}–${Number(((r.range?.start_seconds??0)+(r.range?.duration_seconds??0)).toFixed(2))} sec`;
 return <div className="request-input-row"><div className="request-input-top"><AssetThumbnail id={r.asset_id} name={label} onOpen={onPreview}/><div className="request-input-copy"><strong>{onInsert?<button type="button" className="input-label-insert" title="Insert at cursor" onClick={onInsert}>{label}</button>:label}</strong><span>{summary}</span>{r.kind==='video'&&<small>{r.include_audio?'Source audio included':'Source audio off'}</small>}</div><button type="button" className="input-edit" aria-label={`Edit ${label}`} aria-expanded={editing} onClick={()=>setEditing(!editing)}>{editing?'Done':'Edit'}</button><details ref={menu} className="input-overflow" onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();e.preventDefault();e.currentTarget.open=false;}}}><summary aria-label={`More options for ${label}`} title={`More options for ${label}`}>⋯</summary><div>{[['File information',()=>setInfo(!info),false],['Move up',()=>move(-1),first],['Move down',()=>move(1),last],['Remove',remove,false]].map(([text,action,disabled])=><button key={String(text)} type="button" disabled={Boolean(disabled)} className={text==='Remove'?'input-remove':''} onClick={e=>{e.currentTarget.closest('details')!.open=false;(action as ()=>void)();}}>{String(text)}</button>)}</div></details></div>
 {editing&&<div className="input-edit-fields">{r.kind==='image'?<><label>Role<select aria-label={`${label} role`} value={r.role} onChange={e=>change({role:e.target.value as Ref['role']})}><option value="reference">Reference</option>{editingImage?<option value="source">Source image</option>:<><option value="first_frame">First frame</option><option value="last_frame">Last frame</option></>}</select></label>{!editingImage&&<label>Framing<select aria-label={`${label} framing`} value={r.framing??'fit'} onChange={e=>change({framing:e.target.value as 'fit'|'fill'})}><option value="fit">Fit</option><option value="fill">Fill</option></select></label>}</>:<>{(['start_seconds','duration_seconds'] as const).map(key=><label key={key}>{key==='start_seconds'?'Start time (sec)':'Clip length (sec)'}<input type="number" min={key==='start_seconds'?0:2} max={key==='start_seconds'?undefined:15} step="0.1" value={r.range?.[key]??0} onChange={e=>change({range:{start_seconds:r.range?.start_seconds??0,duration_seconds:r.range?.duration_seconds??2,[key]:Number(e.target.value)}})}/></label>)}{r.kind==='video'&&<label className="input-audio-check"><input type="checkbox" checked={r.include_audio??false} onChange={e=>change({include_audio:e.target.checked})}/>Include source audio</label>}</>}</div>}
 {info&&<div className="input-file-info"><strong>File information</strong><p>{asset?.name??'No longer available'}</p>{asset?.metadata?.width&&asset.metadata.height&&<p>{asset.metadata.width} × {asset.metadata.height} px</p>}{r.kind!=='image'&&asset?.metadata?.duration!==undefined&&<p>Duration: {asset.metadata.duration} sec</p>}{asset?.note&&<p>{asset.note}</p>}</div>}</div>;
}
export function RequestInputs({references,assets,onChange,onPreview,labels,onInsert,editingImage=false}:{editingImage?:boolean;labels?:Map<string,string>;onInsert?:(token:string)=>void;references:Ref[];assets:RequestAsset[];onChange:(refs:Ref[])=>void;onPreview:PreviewRequestInput}){
 const [picker,setPicker]=useState(false),[query,setQuery]=useState('');
 const available=assets.filter(a=>(!editingImage||a.kind==='image')&&a.name.toLowerCase().includes(query.toLowerCase()));
 function add(a:RequestAsset){onChange([...references,{id:clientId(),asset_id:a.id,kind:a.kind,role:editingImage&&!references.length?'source':'reference',...(a.kind==='image'?(editingImage?{}:{framing:'fit' as const}):{range:{start_seconds:0,duration_seconds:Math.min(15,a.metadata?.duration??2)}})}]);setPicker(false);setQuery('');}
 return <section className="review-inputs compact-request-inputs"><h3>Inputs</h3>{references.map((r,i)=><InputRow editingImage={editingImage} key={r.id} reference={r} label={labels?.get(r.id)?.slice(1,-1)??`${kindName(r.kind)} ${references.slice(0,i+1).filter(v=>v.kind===r.kind).length}`} onInsert={labels?.has(r.id)&&onInsert?()=>onInsert(labels.get(r.id)!):undefined} asset={assets.find(a=>a.id===r.asset_id)} first={i===0} last={i===references.length-1} change={v=>onChange(references.map((ref,n)=>n===i?{...ref,...v}:editingImage&&v.role==='source'?{...ref,role:'reference'}:ref))} move={delta=>{const next=[...references];[next[i],next[i+delta]]=[next[i+delta]!,next[i]!];onChange(next);}} remove={()=>onChange(references.filter((_,n)=>n!==i))} onPreview={()=>onPreview(r.asset_id,{inputId:r.id,references})}/>)}<button type="button" disabled={editingImage&&references.length>=10} className="request-add-input" onClick={()=>setPicker(true)}>+ Add input</button>{picker&&<RequestDialog title="Add input" label="Add input" close={()=>setPicker(false)}><input aria-label="Search available inputs" placeholder="Search files in this chat" value={query} onChange={e=>setQuery(e.target.value)}/><div className="input-picker-list">{available.map(a=><button type="button" key={a.id} onClick={()=>add(a)}><span>{kindName(a.kind)}</span><strong>{a.name}</strong></button>)}{!available.length&&<p>{query?'No matching files.':'No other files in this chat. Attach a file in the composer first.'}</p>}</div></RequestDialog>}</section>;
}
