import React,{useEffect,useRef} from 'react';
export function RevisionControls({current,total,onChange,label='revision'}:{current:number;total:number;onChange:(number:number)=>void;label?:string}){return <nav className="revision-controls" aria-label={label+' history'}><button type="button" aria-label={'Previous '+label} disabled={current<=1} onClick={()=>onChange(current-1)}>‹</button><span aria-live="polite">{current}/{total}</span><button type="button" aria-label={'Next '+label} disabled={current>=total} onClick={()=>onChange(current+1)}>›</button></nav>;}
export function EditableItem({children,className,onEdit,label}:{children:React.ReactNode;className:string;onEdit:()=>void;label:string}){
 const menu=useRef<HTMLDivElement>(null),root=useRef<HTMLElement>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),held=useRef(false),origin=useRef({x:0,y:0});
 const cancel=()=>clearTimeout(timer.current);
 useEffect(()=>{function outside(e:PointerEvent){if(!menu.current?.contains(e.target as Node)&&!root.current?.contains(e.target as Node))menu.current?.hidePopover();}document.addEventListener('pointerdown',outside,true);return()=>{cancel();document.removeEventListener('pointerdown',outside,true);};},[]);
 function show(){cancel();held.current=true;const rect=root.current!.getBoundingClientRect(),el=menu.current!;el.style.left=Math.max(8,Math.min(rect.right-40,innerWidth-48))+'px';el.style.top=Math.min(rect.bottom+4,innerHeight-48)+'px';el.showPopover();el.querySelector('button')?.focus();}
 return <article ref={root} className={className} tabIndex={0} onContextMenu={e=>{if((e.target as HTMLElement).closest('button,input,textarea'))return;e.preventDefault();show();}} onPointerDown={e=>{held.current=false;if(e.button!==0||!e.isPrimary||(e.target as HTMLElement).closest('button,input,textarea'))return;origin.current={x:e.clientX,y:e.clientY};timer.current=setTimeout(show,550);}} onPointerMove={e=>{if(Math.hypot(e.clientX-origin.current.x,e.clientY-origin.current.y)>8)cancel();}} onPointerUp={e=>{cancel();if(held.current)e.preventDefault();}} onPointerCancel={cancel} onPointerLeave={cancel} onClickCapture={e=>{if(held.current&&!menu.current?.contains(e.target as Node)){e.preventDefault();e.stopPropagation();held.current=false;}}} onKeyDown={e=>{if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){e.preventDefault();show();}}}>
 {children}<div ref={menu} popover="manual" className="message-edit-popup" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();menu.current?.hidePopover();root.current?.focus();}}}><button type="button" aria-label={label} title={label} onClick={()=>{menu.current?.hidePopover();held.current=false;onEdit();}}><svg aria-hidden="true" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="m15 4 5 5M4 20l5-1L21 7a2 2 0 0 0-4-4L5 15z"/></svg></button></div></article>;
}
