import React,{useEffect,useState} from 'react';
import type {TurnTranscript as Transcript,TurnStep} from '../shared/chat.js';
import {ChatMarkdown} from './chat-markdown.js';
import './turn-transcript.css';
const toolNames:Record<string,string>={read_input:'Inspect input',create_request:'Create request',edit_request:'Edit request',prepare_image:'Image request',animate_image:'Video request',prepare_video:'Video request'};
function toolLabel(step:TurnStep){const input=step.input as {operations?:{operation?:string}[]}|undefined;const op=input?.operations?.[0]?.operation;return op==='create'?'Create request':op==='revise'?'Update request':op==='inspect'?'Read request':toolNames[step.name??'']??step.name??'Tool call';}
function Payload({label,value}:{label:string;value:unknown}){const [copied,setCopied]=useState(false),[error,setError]=useState(false);const text=typeof value==='string'?value:JSON.stringify(value,null,2);return <section className="turn-payload"><header><span>{label}</span><button type="button" onClick={()=>void navigator.clipboard.writeText(text??'').then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1500);}).catch(()=>setError(true))}>{copied?'Copied':'Copy '+label.toLowerCase()}</button></header><pre tabIndex={0}>{text??'Waiting for result…'}</pre>{error&&<small role="alert">Could not copy.</small>}</section>;}
function Tool({step}:{step:TurnStep}){const result=step.result as {content?:{type:string;text?:string}[]}|undefined;const failure=result?.content?.filter(p=>p.type==='text').map(p=>p.text).join(' ');return <details className={'turn-tool '+step.state}><summary><i className={'turn-dot '+step.state}/><span>{toolLabel(step)}</span>{step.state==='failed'&&<small>Rejected</small>}</summary>{step.state==='failed'&&failure&&<p className="turn-tool-error">{(failure.match(/^.*?[.!?](?:\s|$)/)?.[0]??failure.split('\n')[0]??'Tool rejected the request.').slice(0,180)}</p>}<div className="turn-tool-detail"><Payload label="Input" value={step.input}/><Payload label="Result" value={step.result}/></div></details>;}
function ToolGroup({steps}:{steps:TurnStep[]}){return <details className={'turn-tool-group'+(steps.length===1?' single':'')} open><summary hidden={steps.length===1}>Request tools <small>{steps.length} calls</small></summary>{steps.map(step=><Tool key={step.id} step={step}/>)}</details>;}
export function TurnTranscript({turn}:{turn:Transcript}){
 const [now,setNow]=useState(Date.now()),[choice,setChoice]=useState<boolean|null>(null);
 useEffect(()=>{if(turn.state!=='running')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[turn.state]);
 const reasoningLive=turn.state==='running'&&turn.steps.at(-1)?.kind!=='text';
 useEffect(()=>setChoice(null),[reasoningLive,turn.state]);
 const tools=turn.steps.filter(s=>s.kind==='tool'),lastTool=turn.steps.map(s=>s.kind).lastIndexOf('tool'),unresolved=tools.at(-1)?.state==='failed',expanded=choice??(reasoningLive||turn.state==='failed'||(turn.state!=='running'&&unresolved));
 const elapsed=Math.max(0,Math.floor(((turn.ended_at?Date.parse(turn.ended_at):now)-Date.parse(turn.started_at))/1000)),duration=elapsed<60?elapsed+'s':Math.floor(elapsed/60)+'m '+elapsed%60+'s';
 const title=turn.state==='running'?'Working…':turn.state==='stopped'?'Stopped after '+duration:'Worked for '+duration;
 const visible=turn.steps.filter((step,index)=>step.kind!=='text'||index<lastTool);const groups:Array<TurnStep|TurnStep[]>=[];for(const step of visible){if(step.kind==='tool'){const prev=groups.at(-1);if(Array.isArray(prev))prev.push(step);else groups.push([step]);}else groups.push(step);}
 return <section className="turn-transcript"><button type="button" className="turn-toggle" aria-expanded={expanded} onClick={()=>setChoice(!expanded)}>{turn.state==='running'&&<i className="turn-dot running"/>}{title}{turn.state==='running'&&<small>{duration}</small>}<span aria-hidden="true">{expanded?'⌄':'›'}</span></button><div className="turn-steps" hidden={!expanded}>{groups.map(group=>Array.isArray(group)?<ToolGroup key={group[0]!.id} steps={group}/>:<div className="turn-reasoning" key={group.id}><ChatMarkdown text={group.text??''} streaming={turn.state==='running'}/></div>)}{turn.error&&<div className="turn-failure" role="alert">{turn.error}</div>}</div>{turn.state==='running'&&!expanded&&tools.at(-1)?.state==='running'&&<small className="turn-current">{toolLabel(tools.at(-1)!)}…</small>}</section>;
}
